dotnet-store/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace dotnet_store.Controllers;

[Authorize]
public class AdminController : Controller
{
    public ActionResult Index()
    {
        return View();
    }
}

dotnet-store/Controllers/UrunController.cs
using System.Threading.Tasks;
using dotnet_store.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace dotnet_store.Controllers;

public class UrunController : Controller
{
    private readonly DataContext _context;
    public UrunController(DataContext context)
    {
        _context = context;
    }

    public ActionResult Index(int? kategori)
    {
        var query = _context.Urunler.AsQueryable();

        if (kategori != null)
        {
            query = query.Where(i => i.KategoriId == kategori);
        }

        var urunler = query.Select(i => new UrunGetModel
        {
            Id = i.Id,
            UrunAdi = i.UrunAdi,
            Fiyat = i.Fiyat,
            Aktif = i.Aktif,
            Anasayfa = i.Anasayfa,
            KategoriAdi = i.Kategori.KategoriAdi,
            Resim = i.Resim
        }).ToList();

        ViewBag.Kategoriler = new SelectList(_context.Kategori.ToList(), "Id", "KategoriAdi", kategori);

        return View(urunler);
    }

    public ActionResult List(string url, string q)
    {
        var query = _context.Urunler.Where(i => i.Aktif);

        if (!string.IsNullOrEmpty(url))
        {
            query = query.Where(i => i.Kategori.Url == url);
        }

        if (!string.IsNullOrEmpty(q))
        {
            query = query.Where(i => i.UrunAdi.ToLower().Contains(q.ToLower()));

            ViewData["q"] = q;
        }

        return View(query.ToList());
    }

    public ActionResult Details(int id)
    {
        var urun = _context.Urunler.Find(id);

        if (urun == null)
        {
            return RedirectToAction("Index", "Home");
        }

        ViewData["BenzerUrunler"] = _context.Urunler
                                        .Where(i => i.Aktif && i.KategoriId == urun.KategoriId && i.Id != id)
                                        .Take(4)
                                        .ToList();

        return View(urun);
    }

    public ActionResult Create()
    {
        ViewBag.Kategoriler = new SelectList(_context.Kategori.ToList(), "Id", "KategoriAdi");
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(UrunCreateModel model)
    {
        if (model.Resim == null || model.Resim.Length == 0)
        {
            ModelState.AddModelError("Resim", "Resim seçmelisiniz");
        }

        if (ModelState.IsValid)
        {
            var fileName = Path.GetRandomFileName() + ".jpg";
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await model.Resim!.CopyToAsync(stream);
            }

            var entity = new Urun()
            {
                UrunAdi = model.UrunAdi,
                Aciklama = model.Aciklama,
                Fiyat = model.Fiyat ?? 0,
                Aktif = model.Aktif,
                Anasayfa = model.Anasayfa,
                KategoriId = (int)model.KategoriId!,
                Resim = fileName
            };

            _context.Urunler.Add(entity);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        ViewBag.Kategoriler = new SelectList(_context.Kategori.ToList(), "Id", "KategoriAdi");
        return View(model);
    }

    public ActionResult Edit(int id)
    {
        var entity = _context.Urunler.Select(i => new UrunEditModel
        {
            Id = i.Id,
            UrunAdi = i.UrunAdi,
            Aciklama = i.Aciklama,
            Aktif = i.Aktif,
            Anasayfa = i.Anasayfa,
            Fiyat = i.Fiyat,
            KategoriId = i.KategoriId,
            ResimAdi = i.Resim
        }).FirstOrDefault(i => i.Id == id);

        ViewBag.Kategoriler = new SelectList(_context.Kategori.ToList(), "Id", "KategoriAdi");
        return View(entity);
    }

    [HttpPost]
    public async Task<ActionResult> Edit(int id, UrunEditModel model)
    {
        if (id != model.Id)
        {
            return RedirectToAction("Index");
        }

        if (ModelState.IsValid)
        {
            var entity = _context.Urunler.FirstOrDefault(i => i.Id == model.Id);

            if (entity != null)
            {
                if (model.Resim != null)
                {
                    var fileName = Path.GetRandomFileName() + ".jpg";
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/img", fileName);

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await model.Resim!.CopyToAsync(stream);
                    }

                    entity.Resim = fileName;
                }

                entity.UrunAdi = model.UrunAdi;
                entity.Aciklama = model.Aciklama;
                entity.Fiyat = model.Fiyat ?? 0;
                entity.Aktif = model.Aktif;
                entity.Anasayfa = model.Anasayfa;
                entity.KategoriId = (int)model.KategoriId!;

                _context.SaveChanges();

                TempData["Mesaj"] = $"{entity.UrunAdi} ürünü güncellendi.";

                return RedirectToAction("Index");
            }

        }

        ViewBag.Kategoriler = new SelectList(_context.Kategori.ToList(), "Id", "KategoriAdi");
        return View(model);
    }

    public ActionResult Delete(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("Index");
        }

        var entity = _context.Urunler.FirstOrDefault(i => i.Id == id);

        if (entity != null)
        {
            return View(entity);
        }
        return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteConfirm(int? id)
    {
        if (id == null)
        {
            return RedirectToAction("Index");
        }

        var entity = _context.Urunler.FirstOrDefault(i => i.Id == id);

        if (entity != null)
        {
            _context.Urunler.Remove(entity);
            _context.SaveChanges();

            TempData["Mesaj"] = $"{entity.UrunAdi} isimli ürün silindi.";
        }
        return RedirectToAction("Index");
    }


}

dotnet-store/Views/Shared/Partials/_Footer.cshtml
<footer class="mt-3 py-4">
        <div class="container">
            <div class="row gy-3">
                <div class="col-md-6 col-lg-4">
                    <form>
                        <div class="input-group">
                            <input type="email" class="form-control" placeholder="Email giriniz.">
                            <button type="button" class="btn btn-outline-warning">Abone Ol</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-6 col-lg-8">
                    <nav class="text-center text-md-end">
                        <a href="#" class="btn btn-icon btn-outline-warning">
                            <i class="fab fa-facebook"></i>
                        </a>
                        <a href="#" class="btn btn-icon btn-outline-warning">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a href="#" class="btn btn-icon btn-outline-warning">
                            <i class="fab fa-youtube"></i>
                        </a>
                        <a href="#" class="btn btn-icon btn-outline-warning">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </nav>
                </div>
                <div class="col-12">
                    <p class="text-center text-md-start text-white">
                        2026 Tüm hakları saklıdır.
                    </p>
                </div>
            </div>
        </div>
    </footer>

dotnet-store/Views/Shared/Partials/_KonferansCard.cshtml
@model Urun

<div class="card shadow">
    <img src="~/img/@Model.Resim" alt="@Model.UrunAdi" class="card-img-top">
        <div class="border-top info-wrap">
            <a href="#" class="float-end btn btn-light">
                <i class="fa fa-heart"></i>
            </a>
            <a asp-controller="Urun" asp-action="Details" asp-route-id="@Model.Id" class="title text-truncate">@Model.UrunAdi</a>
            <div class="price-wrap">
                <span class="price">@Model.Fiyat</span>
            </div>
        </div>
</div>

dotnet-store/Views/Shared/Partials/_Menu.cshtml
@model List<Kategori>
<nav class="nav nav-pills flex-column flex-nowrap overflow-auto slider_nav">
    @foreach (var kategori in Model)
    {
        <a href="/urunler/@kategori.Url" class="nav-link">@kategori.KategoriAdi</a>
    }
</nav>      

dotnet-store/Views/Shared/Partials/_MuzikCard.cshtml
<div class="card shadow">
                        <img src="img/music2.jpg" alt="music2" class="card-img-top">
                        <div class="border-top info-wrap">
                            <a href="#" class="float-end btn btn-light">
                                <i class="fa fa-heart"></i>
                            </a>
                            <a href="muzik2.html" class="title text-truncate">Dedublüman, 10 Mayıs akşamı Jolly Joker Mersin sahnesinde sizlerle.</a>
                            <div class="price-wrap">
                                <span class="price">3.500</span>
                            </div>
                        </div>
                    </div>

dotnet-store/Views/Shared/Partials/_SporCard.cshtml
<div class="card shadow">
                        <img src="img/spor1.jpg" alt="spor1" class="card-img-top">
                        <div class="border-top info-wrap">
                            <a href="#" class="float-end btn btn-light">
                                <i class="fa fa-heart"></i>
                            </a>
                            <a href="spor1.html" class="title text-truncate">Darüşşafaka Lassa 2024-2025 Sezonu Kombinesi</a>
                            <div class="price-wrap">
                                <span class="price">3.000</span>
                            </div>
                        </div>
                    </div>

dotnet-store/Views/Shared/Partials/_Topbar.cshtml
<section class="top-bar">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2">
                <a href="/" class="navbar-brand">EventEra</a>
            </div>
            <div class="col-lg-5 ">
                <form asp-controller="Urun" asp-action="List" method="get">
                    <div class="input-group">
                        <input name="q" type="text" placeholder="Anahtar Kelime" class="form-control">
                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>

                    </div>
                </form>
            </div>
            <div class="col-lg-5 text-end">
                <div>

                    @if (User.Identity?.IsAuthenticated == true)
                    {
                       
                            <a asp-controller="Admin" asp-action="Index" class="btn btn-danger" target="_blank">
                                <i class="fa-solid fa-lock"></i> <span class="ms-1 d-none d-sm-inline-block">Admin</span>
                            </a>
                        


                        @* <a asp-controller="Account" asp-action="Settings" class="btn btn-light">
                            <i class="fa fa-user"></i> <span class="ms-1 d-none d-sm-inline-block">Hesabım</span>
                        </a> *@
                        <a asp-controller="Account" asp-action="LogOut" class="btn btn-light">
                            <i class="fa fa-heart"></i> <span class="ms-1 d-none d-sm-inline-block">Çıkış</span>
                        </a>
                    }
                    else
                    {
                        <a asp-controller="Account" asp-action="Login" class="btn btn-light">
                            <i class="fa-solid fa-right-to-bracket"></i> <span
                                class="ms-1 d-none d-sm-inline-block">Giriş</span>
                        </a>
                        <a asp-controller="Account" asp-action="Create" class="btn btn-light">
                            <i class="fa-solid fa-user-plus"></i> <span class="ms-1 d-none d-sm-inline-block">Üye Ol</span>
                        </a>
                    }

                    <a asp-controller="Cart" asp-action="Index" class="btn btn-light">
                        <i class="fa fa-shopping-cart"></i> <span class="ms-1 d-none d-sm-inline-block">Sepetim</span>
                    </a>

                    @* @if(User.Identity?.IsAuthenticated == true)
                            {
                            <a href="#" class="btn btn-light">
                                <i class="fa fa-user"></i><span>Hesabım</span>
                            </a>
                            <a href="#" class="btn btn-light">
                                <i class="fa fa-heart"></i><span>Listem</span>
                            </a>
                            }
                            else
                            {
                            <a asp-controller="Account" asp-action="Login" class="btn btn-light">
                                <i class="fa fa-heart"></i><span>Giriş</span>
                            </a>
                            <a asp-controller="Account" asp-action="Login" class="btn btn-light">
                                <i class="fa fa-shopping-cart"></i><span>Üye Ol</span>
                            </a>
                            }
                            <a href="sepetim.html" class="btn btn-light">
                                <i class="fa fa-shopping-cart"></i><span>Sepetim</span>
                            </a> *@

                </div>
            </div>
        </div>
    </div>
</section>